name: app
size: XL
type: php:7.3
disk: 3072
build:
    flavor: composer
relationships:
    database: mysqldb:mysql
    rediscache: rediscache:redis
    redissession: redissession:redis
    solr: solrsearch:eng
variables:
    php:
        date.timezone: America/New_York
    env:
        SYMFONY_ENV: 'prod'
        # We disable Symfony Proxy, as we rather use Varnish
        SYMFONY_HTTP_CACHE: 0
        SYMFONY_TRUSTED_PROXIES: "TRUST_REMOTE"
web:
    locations:
        /:
            root: web
            passthru: /app.php
mounts:
    /var/cache: shared:files/cache
    /var/logs: shared:files/logs
    /var/encore: shared:files/encore
    /web/var: shared:files/var
    /income: shared:files/income
    /.shared: shared:files
runtime:
    sizing_hints:
        request_memory: 20
        reserved_memory: 70
    extensions:
        - imagick
        - xsl
        - redis
        - readline
        - blackfire
hooks:
    build: |
        php bin/console cache:clear --no-warmup
        php bin/console bazinga:js-translation:dump web/assets --merge-domains
        php bin/console assets:install web --symlink --relative

        bash platformsh-utils/bin/bash/node/install.sh 12.11
        bash platformsh-utils/bin/bash/compile_assets/ezplatform2.sh 12.11
    deploy: |
        rm -rf var/cache/*
        php bin/console cache:clear