.global_redirects: &global_redirects
    /_from_test:
        to: /_to_test
        prefix: false

.app: &app
    type: upstream
    upstream: app:http
    cache:
        enabled: false
    ssi:
        enabled: false
    redirects:
        paths:
            <<: *global_redirects

.varnish: &varnish
    <<: *app
    upstream: varnish:http
    ssi:
        enabled: true
    redirects:
        paths:
            <<: *global_redirects

https://www.{default}: *varnish

https://{default}:
    type: redirect
    to: "https://www.{default}/"
