mysqldb:
    type: mysql:10.0
    disk: 1024
    size: L
    configuration:
        schemas:
            - main
        endpoints:
            mysql:
                default_schema: main
                privileges:
                    main: admin
rediscache:
    type: redis:5.0
    configuration:
        maxmemory_policy: volatile-lru
    size: L
redissession:
    type: redis-persistent:5.0
    size: S
    disk: 512
solrsearch:
    type: solr:6.6
    disk: 512
    configuration:
        cores:
            eng:
                conf_dir: !archive "solr/eng"
        endpoints:
            eng:
                core: eng
varnish:
    type: varnish:6.0
    relationships:
        app: app:http
    configuration:
        vcl: !include
            type: string
            path: varnish.vcl